#!/bin/sh

root_path='/home/darwin/conf/'
finjection_folder='finjection'

if [ -d "$root_path$finjection_folder" ]; then
    echo "Folder \"$finjection_folder\" exists. Removing it..."
    rm -R "$root_path$finjection_folder"
fi

ldconfig /usr/local/lib/darwin/
