name: Docker Image CI test

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ master ]

jobs:

  faup:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.5
    steps:
      - uses: actions/checkout@v2
      - name: Build faup docker image
        run: |
          GITHUB_LOWERCASE_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`
          echo "::set-env name=github_lowercase_repo::${GITHUB_LOWERCASE_REPO}"

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: faup
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com/${{ env.github_lowercase_repo }}
          image_tag: ${{ env.VERSION }}
          dockerfile: docker/faup/Dockerfile
          build_extra_args: --build-arg VERSION=${{ env.VERSION }}
        
      - name: test listing docker images
        run: docker images
      - name: test building again
        run: docker build . -t test --cache-from docker.pkg.github.com/frikilax/darwin/faup --build-arg FAUP_VERSION=v1.5 -f docker/faup/Dockerfile
